- ros_topic_name: '/rgbd_camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS  

- ros_topic_name: '/rgbd_camera/depth_image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS  

- ros_topic_name: '/rgbd_camera/camera_info'
  ros_type_name: 'sensor_msgs/msg/CameraInfo'
  gz_type_name: 'ignition.msgs.CameraInfo'
  direction: GZ_TO_ROS  

- ros_topic_name: '/rgbd_camera/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS  

- ros_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'ignition.msgs.Clock'
  direction: GZ_TO_ROS

# Full set of configurations
# - ros_topic_name: "ros_chatter"
#   gz_topic_name: "ign_chatter"
#   ros_type_name: "std_msgs/msg/String"
#   gz_type_name: "ignition.msgs.StringMsg"
#   subscriber_queue: 5       # Default 10
#   publisher_queue: 6        # Default 10
#   lazy: true                # Default "false"
#   direction: BIDIRECTIONAL  # Default "BIDIRECTIONAL" - Bridge both directions
#                             # "GZ_TO_ROS" - Bridge Ignition topic to ROS
#                             # "ROS_TO_GZ" - Bridge ROS topic to Ignition